---
title: "Lab 3"
author: "Erin Cagle"
format: html
editor: visual
---

## 

## 1.

```{r}
download.file(

    "https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz",

    destfile = "met_all.gz",

    method   = "libcurl",

    timeout  = 60 )

met <- data.table::fread("met_all.gz")
```

## 2.

```{r}
dim(met)

head(met)

tail(met)
```

There are 2377343 rows and 30 columns.

## 3.

```{r}
str(met)

```

## 4.

```{r}
table(met$year)

table(met$day)

table(met$hour)
```

```{r}
summary(met$temp)

summary(met$elev)

summary(met$wind.sp)
```

```{r}
met[met$elev==9999.0] <- NA
summary(met$elev)
```

```{r}
met <- met[met$temp != -40.00, ]
met <- met[order(met$temp), ]
head(met)
```

The highest weather station has an elevation of 4113.

## 5.

```{r}
met <- met[met$temp > -15.00, ]
met <- met[order(met$temp), ]
head(met)
```

## 6.

```{r}
elev <- met[elev==max(elev), ]
summary(elev)
```

```{r}
cor(elev$temp, elev$wind.sp, use="complete")
```

```{r}
cor(elev$temp, elev$hour, use="complete")
```

```{r}
cor(elev$wind.sp, elev$day, use="complete")
```

```{r}
cor(elev$wind.sp, elev$hour, use="complete")
```

```{r}
cor(elev$temp, elev$day, use="complete")
```

## 7.

```{r}
hist(met$elev, breaks=100)
```

```{r}
hist(met$temp)
```

```{r}
hist(met$wind.sp)
```

```{r}
leaflet(elev) |>
  addProviderTiles('OpenStreetMap') |> 
   addCircles(lat=~lat,lng=~lon, opacity=1, fillOpacity=1, radius=100)
```

```{r}
library(lubridate)
elev$date <- with(elev, ymd_h(paste(year, month, day, hour, sep= ' ')))
summary(elev$date)
```

```{r}
elev <- elev[order(date)]
head(elev)
```

```{r}
plot(elev$date, elev$temp, type='l')
```

```{r}
plot(elev$date, elev$wind.sp, type='l')
```

## 8.

```{r}
# create a box plot for distribution of temp during night hours (7pm - 11:59pm)
hours <- met[order(met$hour)]
tail(hours)
night <- hours[hours$hour >= 19,]
boxplot(night$temp ~ night$hour, col = "orange")
```
